### ISSUE TITLE
Usage of 'continuation' in debug.rb is deprecated/obsolete

### ISSUE THREAD

**Issue by taylorthurlow** [gosu/ruby-app#10]
The default debug script in the ruby mac app template gives this message:

    /Users/%username%/Downloads/Ruby.app/Contents/Resources/lib/continuation.bundle: warning: callcc is obsolete; use Fiber instead

**Comment by jlnr** [comment]
Thanks for reporting this. I don't see this message anymore with the upcoming 0.14.5 build, so it seems it has fixed itself :)
