### ISSUE TITLE
Build a new .app with Ruby 2.3, SDL 2.0.4 and Gosu 0.10.x

### ISSUE THREAD

**Issue by jlnr** [gosu/ruby-app#6]
Still blocked on SDL 2.0.4 taking its time.

**Comment by jlnr** [comment]
Unblocked by Gosu 0.10.5

**Comment by kaspermeyer** [comment]
Just curious - how is this coming along? I'm looking forward to wrap newer version of Gosu :) 
Would it be possible to bump it to Ruby 2.3 as well?

**Comment by jlnr** [comment]
Once I get to it, I'll naturally use the latest version of Ruby that works (so, probably 2.3 oder 2.3.1) :)

No news though...hopefully I'll be more productive this Sunday/Monday.

**Comment by jlnr** [comment]
A quick update: `rake` fails because `Gosu/src/AppleUtility.hpp` has started using `std::to_string`,  which is part of the C++11 standard library.

There are also warnings about ARC not being used - which is a little scary, I hope I'm not leaking memory like crazy in the OS X gem?

If this turns out to be a lot of trouble, dropping support for 10.7 & 10.8 and upgrading Xcode might help.

**Comment by jlnr** [comment]
No, fixing compilation on 10.7 was quite easy. (I always prefer to build Ruby.app on the oldest VM I have, so that it'll work on every later version of OS X.)

Next step: Releasing a new version of Gosu that includes these fixes, so that it can be bundled with Ruby.app.

**Comment by jlnr** [comment]
Done, see https://github.com/gosu/ruby-app/releases

**Comment by kaspermeyer** [comment]
That's fantastic! Thank you so much for your hard work :) It's appreciated.

**Comment by jlnr** [comment]
np :)
